### Create a person on the development server
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "AD",
  "number": "3999608342"
}

### Create a person on the production server
POST https://phonebook-backend-fso-course-uni-helsinki.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Amlan",
  "number": "3999608342"
}