### Update a person from the development server
PUT http://localhost:3001/api/persons/659370443e6865ec2465316c
Content-Type: application/json

{
  "name": "Ayah",
  "number": "123123"
}

### Update a person from the production server
PUT https://phonebook-backend-fso-course-uni-helsinki.onrender.com/api/persons/659370443e6865ec2465316c
Content-Type: application/json

{
  "name": "Ayah",
  "number": "421321"
}